import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components';



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Teok Final</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img id={styles.bubble} src="/bubble.png" alt="Dialogue bubble" />   
        <text id={styles.bubbletext}>
          Hello! I am Teok!</text>       
        <img id="logowithtext" src="/logowithtext.png" alt="Teok Logo" />
        <p>By Angelyne, Joyce and Kaley</p>
        {/* <h1 className={styles.title}> */}
        {/* </h1> */}



      </main>

      {/* <footer className={styles.footer}>

      </footer> */}
    </div>
  )
}
